@startuml
set namespaceSeparator ::

abstract class "patterns_dart::creational::factory-method::factory-method.dart::IProduct" {
  +String price()
}

abstract class "patterns_dart::creational::factory-method::factory-method.dart::ISeller" {
  +IProduct buyProduct()
}

class "patterns_dart::creational::factory-method::factory-method.dart::MilkSeller" {
  +Milk buyProduct()
}

"patterns_dart::creational::factory-method::factory-method.dart::ISeller" <|-- "patterns_dart::creational::factory-method::factory-method.dart::MilkSeller"

class "patterns_dart::creational::factory-method::factory-method.dart::MeetSeller" {
  +Meet buyProduct()
}

"patterns_dart::creational::factory-method::factory-method.dart::ISeller" <|-- "patterns_dart::creational::factory-method::factory-method.dart::MeetSeller"

class "patterns_dart::creational::factory-method::factory-method.dart::Milk" {
  +String price()
}

"patterns_dart::creational::factory-method::factory-method.dart::IProduct" <|-- "patterns_dart::creational::factory-method::factory-method.dart::Milk"

class "patterns_dart::creational::factory-method::factory-method.dart::Meet" {
  +String price()
}

"patterns_dart::creational::factory-method::factory-method.dart::IProduct" <|-- "patterns_dart::creational::factory-method::factory-method.dart::Meet"


@enduml